# Generated by Django 5.0.7 on 2024-07-10 15:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0002_user_has_set_password'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='has_set_password',
        ),
    ]
